# Generated by Django 2.2 on 2019-05-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('codbarbero', models.AutoField(primary_key=True, serialize=False)),
                ('barberonom', models.CharField(max_length=150)),
                ('fecharegistro', models.DateField()),
                ('descripcion', models.TextField()),
                ('correo', models.EmailField(max_length=250)),
                ('fotobarbero', models.ImageField(null=True, upload_to='fotosbarberos')),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
                'ordering': ['barberonom'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codcliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('clientenom', models.CharField(max_length=150, verbose_name='Cliente')),
                ('fecharegistro', models.DateField()),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=250, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['clientenom'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codserv', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('servicio', models.CharField(max_length=150, verbose_name='Servicio')),
                ('nomcorto', models.CharField(max_length=50, verbose_name='Abreviatura')),
                ('fecharegistro', models.DateField()),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nomcorto'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codreserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('obs', models.TextField()),
                ('codbarbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservaBarberia.Barbero')),
                ('codclie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservaBarberia.Cliente')),
                ('codserv', models.ManyToManyField(to='ReservaBarberia.Servicio')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha'],
            },
        ),
    ]
